version: 2
updates:
  - package-ecosystem: "docker-compose"
    directories: [ "/*/" ]
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependabot"
    groups:
      docker-compose-dependencies:
        patterns:
          - "*"
