services:
  app_proxy:
    environment:
      APP_HOST: 127.0.0.1
  source:
    image: jvstein/bitcoin-prometheus-exporter:v0.9.0@sha256:31ab56a97eb78ebb7743859cbb255971044e182ed4ab76f115aacc68297d5602
