services:
  app_proxy:
    environment:
      APP_HOST: test-default-convention_web_1
  web:
    image: jvstein/bitcoin-prometheus-exporter:v0.9.0@sha256:31ab56a97eb78ebb7743859cbb255971044e182ed4ab76f115aacc68297d5602
