services:
  app_proxy:
    environment:
      APP_HOST: test-dependabot_web_1
  web:
    image: jvstein/bitcoin-prometheus-exporter:v0.9.0@sha256:358132b6967554f4d30a43847bfc5fd941719eb257b2820cf8ebd16405733843
