name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
    steps:
      - name: Create check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/${{ github.repository }}/check-runs -X POST -F name="My Check" -F head_sha=${{ github.sha }} \
            -F status="completed" -F conclusion="failure" \
            -F actions[][label]="Ignore" \
            -F actions[][description]="Ignore the warnings" \
            -F actions[][identifier]="ignore"

      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: mikefarah/yq@v4
        with:
          cmd: yq --version

      - name: Run update-version tests
        working-directory: tests-update-version
        run: ./run-tests.sh

  update-test-umbrel-manifest:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - uses: CPardi/update-umbrel-app-action@master
